FROM golang:1.14-alpine

RUN apk update && apk add --no-cache git mercurial openssh
RUN apk add ca-certificates tzdata

RUN go get github.com/go-delve/delve/cmd/dlv

WORKDIR /app

COPY zoneinfo.zip /app/zoneinfo.zip
ENV ZONEINFO /app/zoneinfo.zip

COPY ./build/service_permissions /app/service_permissions

ENTRYPOINT ["/app/service_permissions"]