// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/permissions/permissions.proto

package permissions

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PermissionReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionKey            string   `protobuf:"bytes,2,opt,name=action_key,json=actionKey,proto3" json:"action_key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionReq) Reset()         { *m = PermissionReq{} }
func (m *PermissionReq) String() string { return proto.CompactTextString(m) }
func (*PermissionReq) ProtoMessage()    {}
func (*PermissionReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98ac53c03f96f01, []int{0}
}

func (m *PermissionReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionReq.Unmarshal(m, b)
}
func (m *PermissionReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionReq.Marshal(b, m, deterministic)
}
func (m *PermissionReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionReq.Merge(m, src)
}
func (m *PermissionReq) XXX_Size() int {
	return xxx_messageInfo_PermissionReq.Size(m)
}
func (m *PermissionReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionReq proto.InternalMessageInfo

func (m *PermissionReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PermissionReq) GetActionKey() string {
	if m != nil {
		return m.ActionKey
	}
	return ""
}

type PermissionsReq struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionKeys           []string `protobuf:"bytes,2,rep,name=action_keys,json=actionKeys,proto3" json:"action_keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionsReq) Reset()         { *m = PermissionsReq{} }
func (m *PermissionsReq) String() string { return proto.CompactTextString(m) }
func (*PermissionsReq) ProtoMessage()    {}
func (*PermissionsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98ac53c03f96f01, []int{1}
}

func (m *PermissionsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionsReq.Unmarshal(m, b)
}
func (m *PermissionsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionsReq.Marshal(b, m, deterministic)
}
func (m *PermissionsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionsReq.Merge(m, src)
}
func (m *PermissionsReq) XXX_Size() int {
	return xxx_messageInfo_PermissionsReq.Size(m)
}
func (m *PermissionsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionsReq.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionsReq proto.InternalMessageInfo

func (m *PermissionsReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PermissionsReq) GetActionKeys() []string {
	if m != nil {
		return m.ActionKeys
	}
	return nil
}

type PermissionResp struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ActionKey            string   `protobuf:"bytes,2,opt,name=action_key,json=actionKey,proto3" json:"action_key,omitempty"`
	IsAllowed            bool     `protobuf:"varint,3,opt,name=is_allowed,json=isAllowed,proto3" json:"is_allowed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PermissionResp) Reset()         { *m = PermissionResp{} }
func (m *PermissionResp) String() string { return proto.CompactTextString(m) }
func (*PermissionResp) ProtoMessage()    {}
func (*PermissionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98ac53c03f96f01, []int{2}
}

func (m *PermissionResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionResp.Unmarshal(m, b)
}
func (m *PermissionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionResp.Marshal(b, m, deterministic)
}
func (m *PermissionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionResp.Merge(m, src)
}
func (m *PermissionResp) XXX_Size() int {
	return xxx_messageInfo_PermissionResp.Size(m)
}
func (m *PermissionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionResp.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionResp proto.InternalMessageInfo

func (m *PermissionResp) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PermissionResp) GetActionKey() string {
	if m != nil {
		return m.ActionKey
	}
	return ""
}

func (m *PermissionResp) GetIsAllowed() bool {
	if m != nil {
		return m.IsAllowed
	}
	return false
}

type PermissionsResp struct {
	Permissions          []*PermissionResp `protobuf:"bytes,1,rep,name=permissions,proto3" json:"permissions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PermissionsResp) Reset()         { *m = PermissionsResp{} }
func (m *PermissionsResp) String() string { return proto.CompactTextString(m) }
func (*PermissionsResp) ProtoMessage()    {}
func (*PermissionsResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98ac53c03f96f01, []int{3}
}

func (m *PermissionsResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PermissionsResp.Unmarshal(m, b)
}
func (m *PermissionsResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PermissionsResp.Marshal(b, m, deterministic)
}
func (m *PermissionsResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PermissionsResp.Merge(m, src)
}
func (m *PermissionsResp) XXX_Size() int {
	return xxx_messageInfo_PermissionsResp.Size(m)
}
func (m *PermissionsResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PermissionsResp.DiscardUnknown(m)
}

var xxx_messageInfo_PermissionsResp proto.InternalMessageInfo

func (m *PermissionsResp) GetPermissions() []*PermissionResp {
	if m != nil {
		return m.Permissions
	}
	return nil
}

type GroupIdsReq struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupIdsReq) Reset()         { *m = GroupIdsReq{} }
func (m *GroupIdsReq) String() string { return proto.CompactTextString(m) }
func (*GroupIdsReq) ProtoMessage()    {}
func (*GroupIdsReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98ac53c03f96f01, []int{4}
}

func (m *GroupIdsReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupIdsReq.Unmarshal(m, b)
}
func (m *GroupIdsReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupIdsReq.Marshal(b, m, deterministic)
}
func (m *GroupIdsReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupIdsReq.Merge(m, src)
}
func (m *GroupIdsReq) XXX_Size() int {
	return xxx_messageInfo_GroupIdsReq.Size(m)
}
func (m *GroupIdsReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupIdsReq.DiscardUnknown(m)
}

var xxx_messageInfo_GroupIdsReq proto.InternalMessageInfo

func (m *GroupIdsReq) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

type Group struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98ac53c03f96f01, []int{5}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type GroupsResponse struct {
	Groups               []*Group `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupsResponse) Reset()         { *m = GroupsResponse{} }
func (m *GroupsResponse) String() string { return proto.CompactTextString(m) }
func (*GroupsResponse) ProtoMessage()    {}
func (*GroupsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_e98ac53c03f96f01, []int{6}
}

func (m *GroupsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupsResponse.Unmarshal(m, b)
}
func (m *GroupsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupsResponse.Marshal(b, m, deterministic)
}
func (m *GroupsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupsResponse.Merge(m, src)
}
func (m *GroupsResponse) XXX_Size() int {
	return xxx_messageInfo_GroupsResponse.Size(m)
}
func (m *GroupsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupsResponse proto.InternalMessageInfo

func (m *GroupsResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func init() {
	proto.RegisterType((*PermissionReq)(nil), "velmie.wallet.permissions.PermissionReq")
	proto.RegisterType((*PermissionsReq)(nil), "velmie.wallet.permissions.PermissionsReq")
	proto.RegisterType((*PermissionResp)(nil), "velmie.wallet.permissions.PermissionResp")
	proto.RegisterType((*PermissionsResp)(nil), "velmie.wallet.permissions.PermissionsResp")
	proto.RegisterType((*GroupIdsReq)(nil), "velmie.wallet.permissions.GroupIdsReq")
	proto.RegisterType((*Group)(nil), "velmie.wallet.permissions.Group")
	proto.RegisterType((*GroupsResponse)(nil), "velmie.wallet.permissions.GroupsResponse")
}

func init() {
	proto.RegisterFile("rpc/permissions/permissions.proto", fileDescriptor_e98ac53c03f96f01)
}

var fileDescriptor_e98ac53c03f96f01 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x93, 0xcf, 0x4e, 0xc2, 0x40,
	0x10, 0xc6, 0x03, 0x15, 0xa4, 0xd3, 0x80, 0xba, 0x17, 0x91, 0xc4, 0x88, 0x3d, 0x18, 0xf4, 0x50,
	0x13, 0xbc, 0x78, 0x15, 0x0f, 0x04, 0x89, 0x89, 0xd9, 0xa3, 0x31, 0x92, 0xda, 0x4e, 0x70, 0xc3,
	0x9f, 0x96, 0xdd, 0x22, 0xe1, 0xd1, 0x7c, 0x3b, 0xa7, 0xdb, 0x06, 0x96, 0x83, 0xd8, 0x78, 0x9b,
	0x9d, 0x99, 0xfd, 0x76, 0x7e, 0xdf, 0xb4, 0x70, 0x29, 0xe3, 0xe0, 0x36, 0x46, 0x39, 0x13, 0x4a,
	0x89, 0x68, 0xae, 0xcc, 0xd8, 0x8b, 0x65, 0x94, 0x44, 0xec, 0xec, 0x0b, 0xa7, 0x33, 0x81, 0xde,
	0xca, 0x9f, 0x4e, 0x31, 0xf1, 0x8c, 0x06, 0xb7, 0x0f, 0xf5, 0x97, 0xcd, 0x91, 0xe3, 0x82, 0x9d,
	0xc2, 0xe1, 0x52, 0xa1, 0x1c, 0x89, 0xb0, 0x59, 0x6a, 0x97, 0x3a, 0x36, 0xaf, 0xa6, 0xc7, 0x41,
	0xc8, 0xce, 0x01, 0xfc, 0x20, 0xa1, 0xae, 0xd1, 0x04, 0xd7, 0xcd, 0xb2, 0xae, 0xd9, 0x59, 0x66,
	0x88, 0x6b, 0xf7, 0x09, 0x1a, 0x5b, 0x21, 0xb5, 0x57, 0xe9, 0x02, 0x9c, 0xad, 0x92, 0x22, 0x29,
	0x8b, 0x8a, 0xb0, 0x91, 0x52, 0xee, 0xd8, 0xd4, 0xe2, 0xa8, 0xe2, 0xff, 0x4e, 0x95, 0x96, 0x85,
	0x1a, 0x11, 0x76, 0xb4, 0xc2, 0xb0, 0x69, 0x51, 0xb9, 0xc6, 0x6d, 0xa1, 0x1e, 0xb2, 0x84, 0xfb,
	0x0e, 0x47, 0x3b, 0x43, 0xd3, 0x4b, 0x43, 0x70, 0x0c, 0x7f, 0xe8, 0x35, 0xab, 0xe3, 0x74, 0xaf,
	0xbd, 0x5f, 0x1d, 0xf4, 0x76, 0x27, 0xe5, 0xe6, 0x6d, 0x97, 0x48, 0xfb, 0x32, 0x5a, 0xc6, 0x83,
	0x50, 0x3b, 0x72, 0x0c, 0x96, 0x08, 0x33, 0x4d, 0x8b, 0xa7, 0xa1, 0xfb, 0x0c, 0x15, 0xdd, 0xc0,
	0x1a, 0x50, 0xce, 0xd9, 0x2c, 0x4e, 0x11, 0x63, 0x70, 0x30, 0xf7, 0x67, 0x98, 0x13, 0xe9, 0x98,
	0xb5, 0xc1, 0x09, 0x51, 0x05, 0x52, 0xc4, 0x29, 0x9e, 0xa6, 0xb1, 0xb9, 0x99, 0x4a, 0x97, 0xa0,
	0xe5, 0x34, 0x0a, 0x0d, 0x80, 0xec, 0x1e, 0xaa, 0x63, 0x9d, 0xc9, 0x49, 0xda, 0x7b, 0x48, 0xf4,
	0x55, 0x9e, 0xf7, 0x77, 0xbf, 0xcb, 0x70, 0xb2, 0x65, 0x7b, 0xfc, 0xc4, 0x60, 0x82, 0x92, 0xbd,
	0x41, 0x45, 0x87, 0xac, 0x53, 0xd0, 0x92, 0x45, 0xab, 0xb8, 0x79, 0xcc, 0x87, 0x9a, 0x56, 0xa7,
	0xfd, 0xb0, 0x62, 0xd7, 0x52, 0x5f, 0x5b, 0x37, 0x45, 0x5b, 0xe9, 0x89, 0x80, 0x2c, 0xc2, 0x24,
	0x73, 0xa9, 0xb7, 0xa6, 0xc5, 0xb0, 0xab, 0xbf, 0x2c, 0xc9, 0xb6, 0xb7, 0x97, 0x63, 0xd7, 0xf5,
	0x5e, 0xfd, 0xd5, 0xfc, 0x0c, 0x3e, 0xaa, 0xfa, 0x37, 0xbc, 0xfb, 0x09, 0x00, 0x00, 0xff, 0xff,
	0x9f, 0x3f, 0x3e, 0x94, 0xab, 0x03, 0x00, 0x00,
}
